global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: goflow2
    static_configs:
      - targets: ["goflow2:8080"]

  - job_name: mytest
    static_configs:
      - targets: ["host.docker.internal:8000"]
